# Generated by Django 6.0.2 on 2026-08-25 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('subject_code', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('exam_session', models.CharField(max_length=10)),
                ('drive_file_id', models.CharField(max_length=100)),
                ('drive_download_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['subject_code', 'year', 'exam_session'],
                'unique_together': {('branch', 'semester', 'subject_code', 'year', 'exam_session')},
            },
        ),
    ]
