# Generated by Django 6.0.2 on 2026-08-25 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pyq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pyq',
            options={'ordering': ['subject_code', 'year', 'exam_session'], 'verbose_name': 'PYQ', 'verbose_name_plural': 'PYQs'},
        ),
    ]
