# Generated by Django 5.2.17 on 2026-09-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pyq_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pyq',
            index=models.Index(fields=['branch', 'semester', 'year'], name='pyq_lookup_idx'),
        ),
    ]
