# Generated by Django 6.0.2 on 2026-09-19 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pyq_pyq_lookup_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pyq',
            name='drive_download_url',
        ),
        migrations.RemoveField(
            model_name='pyq',
            name='drive_file_id',
        ),
        migrations.AddField(
            model_name='pyq',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pyq',
            name='r2_object_key',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.CreateModel(
            name='StudentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20)),
                ('r2_object_key', models.CharField(blank=True, default='', max_length=255)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('ocr_status', models.CharField(choices=[('not_started', 'Not Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='not_started', max_length=20)),
                ('ocr_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_extracted_college_name', models.CharField(blank=True, default='', max_length=255)),
                ('ocr_extracted_roll_number', models.CharField(blank=True, default='', max_length=50)),
                ('ocr_college_match', models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch'), ('not_extracted', 'Not Extracted')], default='not_extracted', max_length=20)),
                ('ocr_roll_match', models.CharField(choices=[('match', 'Match'), ('mismatch', 'Mismatch'), ('not_extracted', 'Not Extracted')], default='not_extracted', max_length=20)),
                ('ocr_college_match_score', models.IntegerField(blank=True, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, default='')),
                ('ocr_error_message', models.TextField(blank=True, default='')),
                ('ocr_warnings', models.JSONField(blank=True, default=list)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Verification',
                'verbose_name_plural': 'Student Verifications',
                'indexes': [models.Index(fields=['status'], name='verification_status_idx'), models.Index(fields=['ocr_status'], name='verification_ocr_idx')],
            },
        ),
    ]
