# Generated by Django 6.0.2 on 2026-09-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_r2_and_verification'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentverification',
            name='verification_ocr_idx',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_college_match',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_college_match_score',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_error_message',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_extracted_college_name',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_extracted_roll_number',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_processed_at',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_raw_text',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_roll_match',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_status',
        ),
        migrations.RemoveField(
            model_name='studentverification',
            name='ocr_warnings',
        ),
    ]
