# Generated by Django 5.2.17 on 2026-09-25 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_studentverification_verification_ocr_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('is_current', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['branch', 'semester', '-is_current', 'code'],
                'indexes': [models.Index(fields=['branch', 'semester', 'is_current'], name='subj_branch_sem_idx'), models.Index(fields=['code'], name='subj_code_idx')],
                'unique_together': {('branch', 'semester', 'code', 'name')},
            },
        ),
        migrations.AddField(
            model_name='pyq',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pyqs', to='core.subject'),
        ),
    ]
