# Generated by Django 5.2.17 on 2026-09-25 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=30)),
                ('semester', models.IntegerField()),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subject Request',
                'verbose_name_plural': 'Subject Requests',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='subj_req_status_idx'), models.Index(fields=['branch', 'semester'], name='subj_req_branch_sem_idx')],
            },
        ),
    ]
