"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import sys
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env', override=True)

# ==============================================================================
# Contributor Mode / Local Development Overrides
# ==============================================================================
# Setting CONTRIBUTOR_MODE=True forces:
#   1. Local SQLite database (ignores remote NeonDB DATABASE_URL)
#   2. Local disk file storage under ./media/ (ignores Cloudflare R2 credentials)
#   3. Local terminal console email output (ignores Resend API key)
CONTRIBUTOR_MODE = os.environ.get('CONTRIBUTOR_MODE', 'False').lower() in ('true', '1')
FORCE_LOCAL_STORAGE = CONTRIBUTOR_MODE or os.environ.get('FORCE_LOCAL_STORAGE', 'False').lower() in ('true', '1')
FORCE_LOCAL_DB = CONTRIBUTOR_MODE or os.environ.get('FORCE_LOCAL_DB', 'False').lower() in ('true', '1')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-getpyqjec-local-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

_host_ip = os.environ.get('VITE_HOST_IP', '')
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
_allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "api.getpyqjec.in",
    "getpyqjec.in",
    "www.getpyqjec.in",
    ".getpyqjec.in",
    ".onrender.com",
]
if _host_ip:
    ALLOWED_HOSTS.append(_host_ip)
if _render_host:
    ALLOWED_HOSTS.append(_render_host)
if _allowed_hosts_env:
    for h in _allowed_hosts_env.split(','):
        h = h.strip()
        if h:
            # Strip scheme and paths if user entered e.g. https://api.getpyqjec.in/
            h = h.replace('https://', '').replace('http://', '').split('/')[0]
            if h and h not in ALLOWED_HOSTS:
                ALLOWED_HOSTS.append(h)

AUTH_USER_MODEL = 'core.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    
    'corsheaders',
    'core',
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

FRONTEND_DIST_DIR = BASE_DIR / "frontend" / "dist"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"] + ([FRONTEND_DIST_DIR] if FRONTEND_DIST_DIR.exists() else []),
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# NeonDB PostgreSQL in production via DATABASE_URL; fallback to SQLite for local development
db_url = os.environ.get('DATABASE_URL')
if FORCE_LOCAL_DB or 'test' in sys.argv or not db_url or db_url.strip() == '':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    ssl_require = ('sqlite' not in db_url)
    DATABASES = {
        'default': dj_database_url.config(
            default=db_url,
            conn_max_age=600,
            ssl_require=ssl_require,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password reset token expiry (5 minutes = 300 seconds)
PASSWORD_RESET_TIMEOUT = 300

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [FRONTEND_DIST_DIR] if FRONTEND_DIST_DIR.exists() else []
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage" if not DEBUG else "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Frontend & CORS Configuration
_default_frontend = 'http://localhost:5173' if (DEBUG or CONTRIBUTOR_MODE) else 'https://www.getpyqjec.in'
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', '').rstrip('/')
if not FRONTEND_BASE_URL or (CONTRIBUTOR_MODE and 'getpyqjec.in' in FRONTEND_BASE_URL):
    FRONTEND_BASE_URL = _default_frontend

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://getpyqjec.in",
    "https://www.getpyqjec.in",
]
if _host_ip:
    CORS_ALLOWED_ORIGINS.append(f"http://{_host_ip}:5173")
if FRONTEND_BASE_URL and FRONTEND_BASE_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_BASE_URL)

extra_cors = os.environ.get('CORS_ALLOWED_ORIGINS')
if extra_cors:
    for o in extra_cors.split(','):
        o = o.strip()
        if o:
            if not o.startswith('http://') and not o.startswith('https://'):
                o = f"https://{o}"
            o = o.rstrip('/')
            if o not in CORS_ALLOWED_ORIGINS:
                CORS_ALLOWED_ORIGINS.append(o)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.getpyqjec\.in$",
    r"^https://.*\.vercel\.app$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_EXPOSE_HEADERS = ["Content-Disposition", "X-missing_years", "X-missing_details"]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://api.getpyqjec.in",
    "https://getpyqjec.in",
    "https://www.getpyqjec.in",
]
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f"https://{_render_host}")
for origin in CORS_ALLOWED_ORIGINS:
    if origin.startswith("http") and origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(origin)

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ==============================================================================
# Email Configuration (Resend API)
# ==============================================================================
RESEND_API_KEY = os.environ.get('RESEND_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'GetPYQ <onboarding@resend.dev>')

# ==============================================================================
# Cloudflare R2 Storage Configuration
# ==============================================================================
R2_ACCOUNT_ID = os.environ.get('R2_ACCOUNT_ID', '')
R2_ACCESS_KEY_ID = os.environ.get('R2_ACCESS_KEY_ID', '')
R2_SECRET_ACCESS_KEY = os.environ.get('R2_SECRET_ACCESS_KEY', '')
R2_ENDPOINT_URL = os.environ.get(
    'R2_ENDPOINT_URL',
    f'https://{R2_ACCOUNT_ID}.r2.cloudflarestorage.com' if R2_ACCOUNT_ID else ''
)
R2_PYQ_BUCKET = os.environ.get('R2_PYQ_BUCKET') or os.environ.get('R2_PYQ_BUCKET_NAME') or 'getpyqjec-pyqs'
R2_VERIFICATION_BUCKET = os.environ.get('R2_VERIFICATION_BUCKET') or os.environ.get('R2_VERIFICATION_BUCKET_NAME') or 'getpyqjec-verifications'
R2_PRESIGNED_URL_EXPIRY = int(os.environ.get('R2_PRESIGNED_URL_EXPIRY', '3600'))

# ==============================================================================
# Verification Image Constraints
# ==============================================================================
VERIFICATION_MAX_IMAGE_SIZE_MB = int(os.environ.get('VERIFICATION_MAX_IMAGE_SIZE_MB', '2'))
VERIFICATION_ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png']

